PyTorch 사용법

In [ ]:
import torch
import torch.nn as nn

input_data = torch.zeros((16, 50))
fc = nn.Linear(50, 10)
output = fc(input_data)
print(input_data)
print(output)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

batch 크기 : 16

채널 수 : 3

이미지의 높이와 너비 : 32, 32의

랜덤한 텐서객체를 생성한다.

-> 16개의 32*32 픽셀 크기를 가진 4차원 텐서가 생성된다.

생성된 다차원구조의 텐서를 1차원 벡터로 변환한다.

그러면 x는 16, 3072 크기의 벡터가 된다.


In [ ]:
input_data = torch.rand((16, 3, 32, 32))
flatten = nn.Flatten()
x = flatten(input_data)
print(input_data)
print(x)

tensor([[[[7.1117e-01, 7.8127e-01, 5.1063e-01,  ..., 3.6511e-01,
           1.4351e-01, 7.0815e-01],
          [8.6056e-01, 4.4347e-01, 3.8368e-01,  ..., 1.4306e-01,
           1.3707e-01, 2.7909e-01],
          [7.9678e-01, 3.9783e-01, 5.5861e-02,  ..., 6.4238e-01,
           9.1238e-02, 1.9995e-01],
          ...,
          [3.8069e-01, 8.4132e-01, 7.0217e-02,  ..., 3.8958e-01,
           3.4661e-01, 1.6956e-01],
          [8.1206e-02, 1.9586e-01, 7.3761e-02,  ..., 8.0972e-01,
           3.6332e-01, 6.4487e-01],
          [8.5637e-01, 6.9285e-01, 2.0268e-01,  ..., 8.7229e-01,
           3.0497e-01, 2.4716e-01]],

         [[2.9962e-01, 7.2628e-01, 2.6178e-01,  ..., 5.6076e-01,
           2.8777e-01, 9.9355e-01],
          [7.7918e-01, 4.2702e-01, 5.8601e-01,  ..., 1.0839e-01,
           7.7223e-01, 5.7506e-01],
          [6.6905e-01, 8.4585e-01, 8.4362e-02,  ..., 6.7860e-01,
           8.7308e-03, 7.4688e-01],
          ...,
          [2.0808e-04, 7.5178e-01, 3.9202e-01,  ..., 6.6510

PyTorch의 torch.nn 모듈을 이용하여 신경망을 구축하기

10차원의 입력을 받아서 50차원의 은닉층을 거쳐 1차원의 출력을 생성하는 간단한 신경망을 정의

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(10, 50)
        self.fc2 = nn.Linear(50, 1)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# 모델 인스턴스 생성
model = SimpleNN()


데이터셋을 처리하고 배치, 셔플링하기

가상의 데이터셋을 생성하고 데이터를 배치 단위로 나누어 처리하는 과정

In [ ]:
from torch.utils.data import DataLoader, TensorDataset

# 샘플 데이터 생성
x_data = torch.randn(100, 10)
y_data = torch.randn(100, 1)

# TensorDataset 및 DataLoader
dataset = TensorDataset(x_data, y_data)
dataloader = DataLoader(dataset, batch_size=5, shuffle=True)

# DataLoader 사용
for batch_idx, (x_batch, y_batch) in enumerate(dataloader):
    print(f'Batch {batch_idx + 1}:')
    print(x_batch)
    print(y_batch)


Batch 1:
tensor([[ 0.1454,  0.0784,  0.7411, -0.5797, -1.0368, -0.6367,  0.3480, -1.5888,
          0.9927,  1.1817],
        [-1.2278, -2.0089,  2.0253, -0.4245,  0.3331, -1.1492,  0.8603, -0.6953,
          0.8314, -0.8285],
        [-0.9838,  2.2872,  0.5214,  1.3060, -0.3941, -0.1307, -0.2072,  0.2032,
          0.6068,  0.7577],
        [ 0.6246,  1.9182,  0.7249,  0.6854,  0.4429, -0.9172,  0.3025, -0.9290,
          0.4720, -1.2261],
        [-0.0959, -0.4425,  1.3125,  0.5122,  0.5116, -0.4249,  0.0087, -0.7668,
         -0.0368,  1.0052]])
tensor([[ 0.4511],
        [-1.1227],
        [ 0.2648],
        [-0.2057],
        [-1.4760]])
Batch 2:
tensor([[-0.4213,  0.3955, -1.2014, -0.4278, -0.0924,  0.8815, -0.7604, -0.1527,
          0.2703,  0.5743],
        [ 0.0491,  0.1751, -0.0832, -0.3385, -0.5072,  0.9449,  0.4953, -1.5073,
          1.1588,  1.3403],
        [-0.6787,  1.1528, -1.0484, -0.3278, -0.5722, -0.6617, -1.7769, -0.3797,
          0.3239, -0.8468],
        [ 0.0

손실 함수 및 최적화 기법 사용

평균제곱오차(MSE)를 손실함수로 사용하고, 확률적 경사하강법(SGD)를 최적화 방법으로 이용하여 모델을 학습시키는 과정

In [ ]:
import torch.optim as optim

# 손실 함수 및 옵티마이저 설정
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# 학습 루프
for epoch in range(10):
    for x_batch, y_batch in dataloader:
        # 순전파
        outputs = model(x_batch)
        loss = criterion(outputs, y_batch)

        # 역전파 및 최적화
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    print(f'Epoch {epoch+1}, Loss: {loss.item()}')


Epoch 1, Loss: 1.671868920326233
Epoch 2, Loss: 0.3105408251285553
Epoch 3, Loss: 1.7902917861938477
Epoch 4, Loss: 0.8937380909919739
Epoch 5, Loss: 0.559956431388855
Epoch 6, Loss: 0.6858763098716736
Epoch 7, Loss: 0.7428311109542847
Epoch 8, Loss: 1.7082622051239014
Epoch 9, Loss: 0.45067280530929565
Epoch 10, Loss: 0.7971304059028625


모델의 성능을 평가하고 학습된 모델을 저장 및 불러오기

저장된 모델을 불러와 새로운 데이터에 대한 예측을 할 수 있음.

In [ ]:
# 평가 모드로 전환
model.eval()

# 평가
with torch.no_grad():
    total_loss = 0
    for x_batch, y_batch in dataloader:
        outputs = model(x_batch)
        loss = criterion(outputs, y_batch)
        total_loss += loss.item()

print(f'Total Loss: {total_loss}')

# 모델 저장
torch.save(model.state_dict(), 'simple_nn.pth')


Total Loss: 16.036434516310692


In [ ]:
# 모델 로드
model = SimpleNN()
model.load_state_dict(torch.load('simple_nn.pth'))
model.eval()

# 예측 수행
with torch.no_grad():
    new_data = torch.randn(1, 10)
    prediction = model(new_data)
    print(f'Prediction: {prediction}')


Prediction: tensor([[0.1973]])


In [4]:
import torch

# 1. 차원 축소 (Squeeze)
tensor = torch.randn(1, 3, 1, 4)
print("Original Tensor:", tensor.shape)

tensor_squeezed = tensor.squeeze()
print("Squeezed Tensor:", tensor_squeezed.shape)

# 2. 차원 확장 (Unsqueeze)
tensor_expanded = tensor_squeezed.unsqueeze(0)
print("Expanded Tensor:", tensor_expanded.shape)

# 3. 축 변경 (Permute)
tensor_permuted = tensor.permute(1, 0, 2, 3)
print("Permuted Tensor:", tensor_permuted.shape)

# 4. 행렬 붙이기 (Concatenate)
tensor_a = torch.randn(2, 3)
tensor_b = torch.randn(2, 3)
tensor_concat = torch.cat((tensor_a, tensor_b), dim=0)
print("Concatenated Tensor:", tensor_concat.shape)

# 5. 행렬 간 연산
tensor_c = torch.randn(2, 3)
tensor_d = torch.randn(2, 3)

# 덧셈
tensor_add = tensor_c + tensor_d
print("Added Tensor:\n", tensor_add)

# 곱셈 (요소별 곱)
tensor_mul = tensor_c * tensor_d
print("Multiplied Tensor:\n", tensor_mul)

# 행렬 곱셈
tensor_matmul = torch.matmul(tensor_c, tensor_d.T)
print("Matrix Multiplication:\n", tensor_matmul)

Original Tensor: torch.Size([1, 3, 1, 4])
Squeezed Tensor: torch.Size([3, 4])
Expanded Tensor: torch.Size([1, 3, 4])
Permuted Tensor: torch.Size([3, 1, 1, 4])
Concatenated Tensor: torch.Size([4, 3])
Added Tensor:
 tensor([[-0.7628, -2.3965,  2.7018],
        [-0.2307,  2.7836, -2.5003]])
Multiplied Tensor:
 tensor([[-0.2666,  1.3008,  1.6830],
        [-0.3143,  1.6407,  1.2419]])
Matrix Multiplication:
 tensor([[ 2.7171, -1.7661],
        [-4.0973,  2.5683]])
